project_id = "pmnqukoifdqiiyctyoof"

[functions.pluggy-connect-token]
verify_jwt = true

[functions.pluggy-list-items]
verify_jwt = true

[functions.pluggy-sync-item]
verify_jwt = true

[functions.pluggy-register-item]
verify_jwt = true

[functions.pluggy-sync-data]
verify_jwt = true